'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError } from '@/lib/api';
import { cn, formatNumber } from '@/lib/utils';

type Active = { mode:'READY'|'ACTIVE'; title:string; description:string|null; passingScore:number; timeLimitMinutes:number|null; questions:Array<{id:string;prompt:string;options:Array<{id:string;text:string}>}>; activeAttempt:{id:string;expiresAt:string|null;answers:Array<{questionId:string;optionId:string|null}>}|null };
type Review = { mode:'REVIEW'; id:string;title:string;score:number;maxScore:number;percentage:number;passed:boolean;status:string;correctCount:number;questionCount:number;attemptCount:number;maxAttempts:number;canRetry:boolean;answers:Array<{questionId:string;prompt:string;explanation:string|null;selectedText:string|null;isCorrect:boolean;correctOption:{id:string;text:string}|null}> };
type Response = Active | Review;

export function AssessmentRunner({id}:{id:string}) {
  const client=useQueryClient(), [answers,setAnswers]=useState<Record<string,string>>({}), [remaining,setRemaining]=useState<number|null>(null), [confirming,setConfirming]=useState(false);
  const query=useQuery({queryKey:['assessment',id],queryFn:()=>api.get<Response>(`/assessments/${id}`)});
  const start=useMutation({mutationFn:()=>api.post<Response>(`/assessments/${id}/start`),onSuccess:data=>client.setQueryData(['assessment',id],data)});
  const submit=useMutation({mutationFn:()=>api.post<Review>(`/assessments/${id}/submit`,{answers:Object.entries(answers).map(([questionId,optionId])=>({questionId,optionId}))}),onSuccess:data=>{setConfirming(false);client.setQueryData(['assessment',id],data);void client.invalidateQueries({queryKey:['student-assessments']});}});
  const assessment=query.data;
  useEffect(()=>{if(assessment?.mode==='ACTIVE'&&assessment.activeAttempt)setAnswers(Object.fromEntries(assessment.activeAttempt.answers.filter(a=>a.optionId).map(a=>[a.questionId,a.optionId!])));},[assessment]);
  useEffect(()=>{if(assessment?.mode!=='ACTIVE'||!assessment.activeAttempt?.expiresAt){setRemaining(null);return;}const tick=()=>{const value=Math.max(0,Math.ceil((new Date(assessment.activeAttempt!.expiresAt!).getTime()-Date.now())/1000));setRemaining(value);if(value===0&&!submit.isPending)submit.mutate();};tick();const timer=window.setInterval(tick,1000);return()=>window.clearInterval(timer);},[assessment,submit]);
  const choose=(questionId:string,optionId:string)=>{setAnswers(current=>({...current,[questionId]:optionId}));void api.post(`/assessments/${id}/save`,{answers:[{questionId,optionId}]}).catch(()=>undefined);};
  if(query.isLoading)return <div className="skeleton h-80 rounded-2xl"/>;
  if(query.isError||!assessment)return <div role="alert" className="rounded-2xl bg-red-500/10 p-6 text-center font-bold text-red-700">تعذر فتح الامتحان. قد يحتاج للشراء أو انتهت إتاحته.<br/><Link className="underline" href="/dashboard/assessments">العودة</Link></div>;
  if(assessment.mode==='REVIEW')return <ReviewResult result={assessment} onRetry={()=>start.mutate()} retrying={start.isPending}/>;
  if(assessment.mode==='READY')return <div className="mx-auto max-w-2xl rounded-3xl border border-gold-500/25 bg-white p-8 text-center dark:bg-midnight-950/75"><h1 className="font-display text-3xl font-black">{assessment.title}</h1>{assessment.description&&<p className="mt-3">{assessment.description}</p>}<div className="mt-5 flex justify-center gap-2 text-sm font-bold"><span className="rounded-lg bg-gold-500/10 px-3 py-2">{formatNumber(assessment.questions.length)} سؤال</span><span className="rounded-lg bg-gold-500/10 px-3 py-2">{assessment.timeLimitMinutes?`${formatNumber(assessment.timeLimitMinutes)} دقيقة`:'بدون وقت محدد'}</span></div><p className="mt-5 text-sm text-midnight-500 dark:text-ivory-300/65">الوقت يبدأ عند الضغط ويستمر عند الخروج. يمكنك العودة لإكمال نفس المحاولة.</p><button onClick={()=>start.mutate()} disabled={start.isPending} className="mt-6 min-h-12 w-full rounded-xl bg-gold-500 font-black text-midnight-950">ابدأ الامتحان الآن</button></div>;
  const answered=Object.keys(answers).length, allAnswered=answered===assessment.questions.length;
  return <div className="mx-auto max-w-3xl space-y-5"><header className="sticky top-28 z-20 rounded-2xl border border-gold-500/30 bg-white/95 p-4 shadow-card backdrop-blur dark:bg-midnight-950/95"><div className="flex items-center justify-between gap-3"><div><Link href="/dashboard/assessments" className="text-xs font-bold text-gold-700">الخروج — إجاباتك محفوظة</Link><h1 className="text-xl font-black">{assessment.title}</h1></div>{remaining!==null&&<div role="timer" className={cn('rounded-xl px-4 py-2 text-xl font-black tabular-nums',remaining<=60?'bg-red-500/15 text-red-600':'bg-gold-500/15 text-gold-700')}>{String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</div>}</div><p className="mt-2 text-xs">أجبت عن {formatNumber(answered)} من {formatNumber(assessment.questions.length)} — حفظ تلقائي</p></header><form onSubmit={e=>{e.preventDefault();if(allAnswered)setConfirming(true);}} className="space-y-4">{assessment.questions.map((q,i)=><fieldset key={q.id} className="rounded-2xl border border-gold-500/20 bg-white p-5 dark:bg-midnight-950/75"><legend className="font-black">{formatNumber(i+1)}. {q.prompt}</legend><div className="mt-4 space-y-2">{q.options.map(o=><label key={o.id} className={cn('flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-4 py-3 font-bold',answers[q.id]===o.id?'border-gold-500 bg-gold-500/10':'border-midnight-200 dark:border-white/10')}><input type="radio" name={q.id} checked={answers[q.id]===o.id} onChange={()=>choose(q.id,o.id)} className="h-5 w-5 accent-[#c99a30]"/>{o.text}</label>)}</div></fieldset>)}{submit.isError&&<p className="bg-red-500/10 p-3 text-red-700">{submit.error instanceof ApiError?submit.error.message:'تعذر التسليم'}</p>}<button disabled={!allAnswered||submit.isPending} className="min-h-12 w-full rounded-xl bg-gold-500 font-black text-midnight-950 disabled:opacity-45">{allAnswered?'تسليم الامتحان':`أكمل ${formatNumber(assessment.questions.length-answered)} إجابة`}</button></form>{confirming&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-midnight-950/75 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 dark:bg-midnight-900"><h2 className="text-xl font-black">تسليم نهائي؟</h2><p className="mt-2 text-sm">بعد التسليم ستدخل للمراجعة والنتيجة فقط.</p><div className="mt-5 flex gap-2"><button onClick={()=>submit.mutate()} className="min-h-11 flex-1 rounded-xl bg-gold-500 font-black">تأكيد</button><button onClick={()=>setConfirming(false)} className="min-h-11 rounded-xl border px-4">رجوع</button></div></div></div>}</div>;
}

function ReviewResult({result,onRetry,retrying}:{result:Review;onRetry:()=>void;retrying:boolean}){return <div className="mx-auto max-w-3xl space-y-5"><section className="rounded-3xl border border-gold-500/25 bg-white p-7 text-center dark:bg-midnight-950/75"><p className="font-black text-gold-700">النتيجة النهائية</p><p className="mt-2 text-6xl font-black">{formatNumber(result.percentage)}%</p><p className="mt-3 text-lg font-black">حليت صح {formatNumber(result.correctCount)} من {formatNumber(result.questionCount)} سؤال</p><p className="text-sm">{formatNumber(result.score)} من {formatNumber(result.maxScore)} درجة</p><p className="mt-2 text-xs text-midnight-500 dark:text-ivory-300/65">المحاولة {formatNumber(result.attemptCount)} من {formatNumber(result.maxAttempts)}</p>{result.canRetry&&<button type="button" onClick={onRetry} disabled={retrying} className="mt-5 min-h-12 rounded-xl border border-gold-500/40 px-6 font-black text-gold-800 disabled:opacity-50 dark:text-gold-300">{retrying?'بنجهّز محاولة جديدة…':'ابدأ محاولة جديدة'}</button>}</section>{result.answers.map((a,i)=><article key={a.questionId} className={cn('rounded-2xl border bg-white p-5 dark:bg-midnight-950/75',a.isCorrect?'border-emerald-500/35':'border-red-500/35')}><div className="flex justify-between gap-3"><h2 className="font-black">{formatNumber(i+1)}. {a.prompt}</h2><span className={a.isCorrect?'text-emerald-600':'text-red-600'}>{a.isCorrect?'صحيحة':'خطأ'}</span></div><p className="mt-3">إجابتك: <strong>{a.selectedText??'لم تتم الإجابة'}</strong></p>{!a.isCorrect&&<p className="mt-2 text-emerald-600">الإجابة الصحيحة: <strong>{a.correctOption?.text}</strong></p>}{a.explanation&&<p className="mt-3 rounded-xl bg-gold-500/10 p-3">التوضيح: {a.explanation}</p>}</article>)}<Link href="/dashboard/assessments" className="flex min-h-12 items-center justify-center rounded-xl bg-gold-500 font-black text-midnight-950">العودة للنتائج</Link></div>}
