export const HISTORY_GRADES = [
  {
    level: 'SEC_1' as const,
    educationSystem: 'GENERAL' as const,
    nameAr: 'الصف الأول الثانوي',
    nameEn: 'First Secondary Grade',
    shortNameAr: 'أولى ثانوي',
    shortNameEn: 'First Secondary',
    slug: 'first-secondary',
    themeKey: 'pharaonic-dawn',
    description: 'حضارة مصر والعالم القديم — من الفراعنة لليونان والرومان',
    descriptionEn: 'Egypt and the ancient world — from the Pharaohs to Greece and Rome',
    sortOrder: 1,
  },
  {
    level: 'SEC_2' as const,
    educationSystem: 'GENERAL' as const,
    nameAr: 'الصف الثاني الثانوي',
    nameEn: 'Second Secondary Grade',
    shortNameAr: 'تانية ثانوي',
    shortNameEn: 'Second Secondary',
    slug: 'second-secondary',
    themeKey: 'renaissance-atlas',
    description: 'أوروبا الحديثة والعالم العربي تحت الحكم العثماني',
    descriptionEn: 'Modern Europe and the Arab world under Ottoman rule',
    sortOrder: 2,
  },
  {
    level: 'SEC_3' as const,
    educationSystem: 'GENERAL' as const,
    nameAr: 'الصف الثالث الثانوي',
    nameEn: 'Third Secondary Grade',
    shortNameAr: 'تالتة ثانوي',
    shortNameEn: 'Third Secondary',
    slug: 'third-secondary',
    themeKey: 'modern-egypt-archive',
    description: 'تاريخ مصر الحديث والمعاصر — سنة الامتحان',
    descriptionEn: 'Modern and contemporary Egyptian history — examination year',
    sortOrder: 3,
  },
  {
    level: 'BACC_1' as const,
    educationSystem: 'BACC' as const,
    nameAr: 'الصف الأول بكالوريا',
    nameEn: 'First Baccalaureate Grade',
    shortNameAr: 'أولى بكالوريا',
    shortNameEn: 'First Baccalaureate',
    slug: 'first-baccalaureate',
    themeKey: 'bacc-foundations',
    description: 'حضارة مصر والعالم القديم بنظام البكالوريا المصرية',
    descriptionEn: 'Egypt and the ancient world in the Egyptian Baccalaureate pathway',
    sortOrder: 1,
  },
  {
    level: 'BACC_2' as const,
    educationSystem: 'BACC' as const,
    nameAr: 'الصف الثاني بكالوريا',
    nameEn: 'Second Baccalaureate Grade',
    shortNameAr: 'تانية بكالوريا',
    shortNameEn: 'Second Baccalaureate',
    slug: 'second-baccalaureate',
    themeKey: 'revolution-chronicle',
    description: 'مصر الحديثة والمعاصرة — ثورة يوليو والتحولات الكبرى',
    descriptionEn: 'Modern and contemporary Egypt — the July Revolution and major transformations',
    sortOrder: 2,
  },
];
